"""followers

Revision ID: 06389b0e4583
Revises: 0687f67cd144
Create Date: 2018-05-02 08:52:35.862389

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06389b0e4583'
down_revision = '0687f67cd144'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
